<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2017-03-28T14:14:36+02:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      api_keys.google.maps
 * @group     app
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'api_keys' => [
        'google' => [
            'maps' => 'AIzaSyAuKJF7UvNTu4itPGdOxzY-uMKEE1gOr9I',
        ],
    ],
];
